### ISSUE TITLE
JWT library with flexible signers

### ISSUE THREAD

**Issue by kdimak** [hyperledger/aries-framework-go#1264]
We use https://github.com/square/go-jose to deal with JWT in `verifiable` package.
In order to sign the JWT, `go-jose` requires creation of `Signer` object with the mandatory passing of a private key.  We would like to deal with private keys inside KMS solely and thus this approach does not satisfy us. 

Requirements for the light-weight impl of the JWT:
- `Signer` interface does not require private key.
- Support JWS and unsecured JWT.
- Support detached payloads (to be used by `signature` package.
- Support `b64` header.
- Support RS256 and EdDSA verifications from the box (as they are used in `verifiable`).
- To be opened for extra algorithms (e.g. secp256k1).

**Comment by kdimak** [comment]
Follow-up issues:
- [ ] Use crypto for "jwt" package for signing/verification logichttps://github.com/hyperledger/aries-framework-go/issues/1278
- [ ] JWT: ECDSA to support NIST P256 curve (https://github.com/hyperledger/aries-framework-go/issues/1266)
- [ ] Pluggable JWS verifiers (https://github.com/hyperledger/aries-framework-go/issues/1267)
