### ISSUE TITLE
CredentialStatus check : DIDComm route

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#1454]
## Summary

We use DIDComm routers to solve the "phone home" problem when third parties check the status of the user's credentials.

The router and the issuer are connected to each other via a modified version of the introduce protocol with the user serving the role of the introducer.

This version of the introduce protocol has the response message containing routing information for the user to save and eventually ensure the credential status method in the Verifiable Credential received from the Issuer contains this routing information. It also contains a one-time-password.

We use the new Out-Of-Band protocol to trigger an automatic route registration request from the Issuer to the Router. This registration request contains non-repudiable proof of the User brokering the one-time-password between the Router and the Issuer.

## References

* [route-coordination RFC](https://github.com/hyperledger/aries-rfcs/blob/12dbe0ff4593e291eeae03ac58ecb7cf327c97a9/features/0211-route-coordination/README.md) (we're using an outdated version)
* [out-of-band RFC](https://github.com/hyperledger/aries-rfcs/blob/f0ec8ef7ca396caa56e34e0ab1a808f4d8889c96/features/0434-outofband/README.md) (pull request)
* [introduce RFC](https://github.com/hyperledger/aries-rfcs/blob/master/features/0028-introduce/README.md)
* [did-exchange RFC](https://github.com/hyperledger/aries-rfcs/blob/master/features/0023-did-exchange/README.md)
* [attachments RFC](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0017-attachments/README.md)
* [DIDComm DID Document Service Conventions](https://github.com/hyperledger/aries-rfcs/blob/master/features/0067-didcomm-diddoc-conventions/README.md#service-conventions)

## Roles

* Holder: the end-user's Aries Agent/Wallet application
* Issuer: the entity that will eventually issue a Verifiable Credential to the Holder
* Router: a software component that routes incoming DIDComm messages to other Aries Agents via pre-registered routes

## Pre-requisites

* The Holder has established a connection to the Router
* The Holder has established a connection to the Issuer

## Choreography

<details><summary>plantuml</summary>
<p>

```
@startuml
actor Holder as user
participant Router as router
participant Issuer as issuer

group introduce protocol
  user -> router : introduce.proposal
  router -> user : introduce.response (oob.request_template + routing + OTP)
  user -> user : JWS(hash(OTP))
  user -> user : inject jws -> oob.request_template
  user -> issuer : introduce.proposal (+ purpose)
  issuer -> user : introduce.response (approve)
  user -> issuer : oob.request
end
issuer -> issuer : extract oob.request.invitation as invitation
issuer -> issuer : extract oob.request.request as route-request
group did-exchange protocol
  issuer -> router : did-exchange.request
  router -> issuer : did-exchange.response
  issuer -> router : did-exchange.ack
end
group route-coordination protocol
  issuer -> router : route-request
  router -> issuer : route-grant
end
group issue-credential (later, out of scope)
  issuer -> user : issue-credential(vc)
  user -> user : checkCredentialStatus(vc)
  user -> user : save(vc)
end
@enduml
```
</p>
</details>

![flow](http://www.plantuml.com/plantuml/png/ZPE_JiCm4CRtFCMDGILz00PKYGLOG1I94HddIDocFcEVGnyVnuw2gQpIfRta-zsVy-Ti70lB_Z1KGZ9PkAUXHGl2WNTeAnD49PKHck65F2V9XkX4V73E9r75gAgwG1bGcYsrNY8OIqoIXWfYQMXkvpfmyqkj0sN8YK0bDNAHpocBpf1s23NHHtZwykZudV5W1i48gvYhT1UYfzVdgwNbKkhnRLltmlNr91TqfNSe6NRVRdfPQfBbn8tBQq2z0kDjY35qYUI_AmaJiiV05pfaarIesseMSWIFR8Na75qhFIeMh4X7XvQdI_Fd_yNxPdunczogji6Zx8NkSfzJpRzEv-YoIUPrp2cHwNGkA2haFXvD6YsDAubigtJS-Vo0SyBPoHBIMQ4vwnJbHbfiKREQh9-kYRs6G0DzWfDaofVWDBCUPU5AoXxb_cw1jYpOkpBgn8YJ4gVRX9_mVVy0 "flow")

## Tasks

- [ ] Out-Of-Band protocol
  - [ ] client package
- [ ] Introduce
  - [ ] hook out-of-band into introduce
  - [ ] modify `proposal` and `response`
  - [ ] save OTP and routing info, inject jws(sha256(otp)) into oob-request
- [ ] route-coordination protocol
  - [ ] `route-grant` returns pre-registered route if `preapproval` is present and valid in `route-request`
- [ ] BDD tests
