### ISSUE TITLE
Add Chacha JWE Content encryption

### ISSUE THREAD

**Issue by Baha-sk** [hyperledger/aries-framework-go#1684]
The new JWE encryption supports P-256 content encryption only. 

Add support for Chacha JWE Content encryption as well.

Requires: 
 - [x] Rename ECDHES Tink key types to include curve names #1804
 - [x] Create new Chacha key protos for ECDHES Tink templates #1805
 - [x] Create New Chacha Key private/public key Managers for ECDHES Tink key type #1806
 - [x] Add chacha key templates #1637
 - [ ] Add new ECDH KMS key types #2447
 - [x] Add support for X25519 key wrapping in ECDH Tink key #2445

ensure this issue is closed when closing this issue:  #815
