### ISSUE TITLE
Support BBS+ Signatures 2020

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-framework-go#1725]
https://w3c-ccg.github.io/ldp-bbs2020/

**Comment by kdimak** [comment]
Remaining work:
- [ ] BBS+ signature verifier #2221 
- [ ] BBS+ signature signer #2222 
- [ ] BSS+ signature suite interop tests (with Mattr) #2223 
- [ ] BSS+ selective disclosure #2224
