### ISSUE TITLE
Create Wrap/UnWrap functions in crypto api

### ISSUE THREAD

**Issue by Baha-sk** [hyperledger/aries-framework-go#2256]
- [x] add new api functions #2257
- [x] add ECDH-1PU wrapping to Wrap/Unwrap #2271
- [ ] remove key wrapping from ecdhes Tink keys, remove `ecdh1pu` package and rename `ecdhes` to be `ecdh` #2299
- [ ] update JWEEncrypter to break JWE creation into 3 steps: create CEK, wrap CEK for each recipient using `Crypto.Wrap()` and finally encrypt plaintext and build JWE  #2300
- [ ] update JWEDecrypter to break JWE parsing into 3 opposite steps  #2300
- [ ] update Packer  #2301
- [ ] update EDV  #2301
