### ISSUE TITLE
Introduce protocol - items that need to be done

### ISSUE THREAD

**Issue by soluchok** [hyperledger/aries-framework-go#882]
- [x] Implement logic in did-exchange service for forwarding an invitation and notify introducee after receiving an invitation (**required**) https://github.com/hyperledger/aries-framework-go/issues/954
- [x] Possibility to finish state machine by the did-exchange (**required**)
- [x] Add validation to the service for incoming messages (e.g response message `approval` false) #935  (**required**)
- [x] Add possibility to pass `To` structure to the `Proposal` message (probably dependency interface need to be changed)  (**required**) #945 
- [x] Specify `senderVerKey` on outbound messages (**required**) https://github.com/hyperledger/aries-framework-go/issues/963
- [x] Reply on an inbound message (get destination) (**required**) https://github.com/hyperledger/aries-framework-go/issues/963
- [x] BDD tests (**required**) https://github.com/hyperledger/aries-framework-go/issues/979

#1022 lists additional followup items.
