### ISSUE TITLE
Verifiable Credential remaining work

### ISSUE THREAD

**Issue by kdimak** [hyperledger/aries-framework-go#886]
Community requests:
- [ ] Feat: Convert Verifiable Credential into Verifiable Presentation #861 
- [ ] Verify JWS when creating new presentation #862 
- [ ] Support LD-Signatures for VC's and VP's #864 (duplicates #174)

Created by members:
- [ ] Add GoDoc documentation with examples to verifiable package #856
- [ ] Support JSON Web Token (JWT) with ES256K (secp256k1) signature #381
- [ ] Refactoring creation of serialized JWT from Verifiable Credential #339
- [ ] Linked Data proof of Verifiable Credential #174
- [ ] A cache of custom credential schemas of Verifiable Credential #185
- [ ] Zero Knowledge Proof of Verifiable Credential (with Verifiable Presentation) #180 
- [ ] Rich Schema for Verifiable Credentials #182
- [ ] Improve Verifiable Credential extension via type embedding #847
