### ISSUE TITLE
Route Coordination - Integrate Service with Framework

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#948]
Integrate [Route Coordination service](https://github.com/hyperledger/aries-framework-go/tree/master/pkg/didcomm/protocol/route) with framework options.
 - [x]  Register agent on the router (client pkg)  #998 #1031 #1072 #1077 
-  [x] Update Recipient key with the Router #1073 
 - [x]  Router Endpoint/Keys Config fetch from Route Service #1095 
 - [x] Integrate Route Service with DIDExchange Invitation #1086 
 - [x] Integrate Route Service with DIDExchange Request #1100  

related to #837

**Comment by rolsonquadras** [comment]
All the related issues/features are completed. Closing this issue.
