### ISSUE TITLE
add Pluggable service provider interfaces (SPI) and default implementations

### ISSUE THREAD

**Issue by Baha-sk** [hyperledger/aries-framework-go#977]
Aries Framework should support pluggable services provider interfaces for Crypto/KMS  operations  as per the Hyperledger wiki (Phase 1) [design](https://wiki.hyperledger.org/display/ARIES/Crypto+and+KMS+as+pluggable+Service+Provider+Interfaces)

The following are action items needed to implement this design

- [x] Add Common/Crypto service SPI #983
- [x] Add Crypto SPI (using Tink API) and its default implementation #984
- [x] Add KMS and SecretLock APIs and their default local implementations #985 
	- [x] Rename existing KMS service to LegacyKMS in framework context #1144
	- [x] Add SecretLock API and mock #1145
	- [x] Add default SecretLock implementation #1146
	- [x] Create a new Storage type with Delete() function #1147
	- [x] Add a new KMS API and mock #1148
	- [x] Add a default (local) KMS implementation with Storage and SecretLock as providers #1149
	- [x] Hook the new KMS in framework and context #1150
	- [x] Update Crypto unit tests to load a KMS with the new key formats #1151

- Add Default implementation for JWE Authcrypt #986 (will be done separately)
- [x] Add Default implementation for JWE Anoncrypt #987
	- [x] Create new Key types to support ECDH-ES primitives (using NIST approved keys) #1469
	- [x] Replace HKDF with ConcatKDF in new ECDH-ES Tink primitive #1472  
	- [x] Update created Tink Key types to return JWE components from crypto primitives #1470

- [x] Add Local Storage implementation of KMS SPI #994
- [x] Create (Keys) Storage Provider interface and implementations #995
- [x] Create Secret Lock provider #996

**Comment by llorllale** [comment]
All tasks completed:

* Crypto: https://github.com/hyperledger/aries-framework-go/tree/master/pkg/crypto
* KMS: https://github.com/hyperledger/aries-framework-go/tree/master/pkg/kms (with legacykms sub package soon to be deprecated)
* JWE: https://github.com/hyperledger/aries-framework-go/tree/master/pkg/doc/jose (jwe files to for building JWE messages)
